fix: use Linio DomainException instead of Symfony HttpException
LinioIT/tortilla pull request #22
Opened 2023-03-14 19:04 UTC by manuelinilo

2023-03-14 19:05 UTC, tamara-dietz requested changes
Can you clarify why this change is needed?

2023-03-14 19:13 UTC, manuelinilo commented
> Can you clarify why this change is needed?

It's because Linio's HttpException previously existed but it's been removed, so my mistake in a previous PR was to replace it with Symfony's HttpException; but the problem is that Tortilla, not being able to capture it through an instanceof, the status code 500 persisted during the execution, giving undesired effects in other systems (like stock-manager for example, where we expect a 400 or any custom code but it always returns a status 500).

2023-03-21 18:08 UTC, maikelsalazar approved these changes

2023-03-22 13:15 UTC, tamara-dietz approved these changes

2023-03-22 13:15 UTC, merged